import './about.css';
import ophiuchus_logo from '../assets/ophiuchus_logo.svg'

function About() {
    const sampleQA = [

        {
            question: "What is this chatbot?",
            answer: "It is a research prototype that provides educational information about common antibiotics using a safe, retrieval-based design. Every answer comes from a pre-validated, expert-reviewed knowledge base rather than being generated by artificial intelligence."
        },
        {
            question: "What can I ask about?",
            answer: "You can ask about uses, side effects, food and alcohol interactions, and antibiotic stewardship."
        },
        {
            question: "What can it not do?",
            answer: "It cannot diagnose illnesses, recommend treatments, replace a doctor, or store your personal data."
        },
        {
            question: "Who are the developers?",
            answer: "The chatbot was developed by 4th Year Computer Science students at Saint Louis University."
        },
        {
            question: "Is it tested?",
            answer: "Yes, the system has been evaluated through both technical performance tests and user usability studies to confirm that it delivers accurate and reliable information within its intended scope."
        },
        {
            question: "Who is it for?",
            answer: "This chatbot is designed for the general public who want to learn about proper antibiotic use. It is not intended as a clinical decision-making tool."
        },
        {
            question: "Can I trust the answers?",
            answer: "All answers come from a validated knowledge base reviewed by healthcare professionals for accuracy and safety."
        },
        {
            question: "Is this medical advice?",
            answer: "No, this information is for general knowledge and should not be taken as medical advice. Consult with a healthcare professional for personalized recommendations."
        }
    ];

    return (
        <>

            <div className="header">
                <img src={ophiuchus_logo} className="" alt="Ophiuchus logo" />
                    <div className="title-container">
                    <p className="title">About</p>
                    <p className="sub-title">Learn more about Ophiuchus</p>
                    </div>
            </div>

            <div className="about-container">
                <div className="cards-container">
                    {sampleQA.map((item, index) => (
                        <div className="qa-card" key={index}>
                            <div className="card-question">
                                <h3>{item.question}</h3>
                            </div>
                            <div className="card-answer">
                                <p>{item.answer}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </>
    );
}

export default About;